### ISSUE TITLE
User can view the letters to type.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/Typing-Test#1]
# Motivation:
So user can see the letters that they are supposed to type.

# Task
- [x] Create HTML/JS files and link with source code.
- [x] Create JS variable
- [x] Add text to variable
