### ISSUE TITLE
User can see prompt for current letter.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/Typing-Test#3]
# Motivation:
User will be able to see a prompt for the next letter in the sentence.

# Tasks:
- [x] Create array from sentence characters.
- [x] Create container element to hold inline element
- [x] Loop through each character and attach to span
- [x] Make sentence appear as soon as page loads
- [x] Show styling on letter to type next
