### ISSUE TITLE
User can type a letter and get feedback.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/Typing-Test#5]
# Motivation:
Change character colors green or red depending if character keyed matches active letter.

# Task
- [x] Add classes/styling in CSS for correct/incorrect typed character
- [x] Create variable to add 'active' class to first character
- [x] Add event listener to trigger function when user begins to type
- [x] Create conditional function comparing user input to active character
- [x] Remove active class and add active class to next character to proceed through sentence
