### ISSUE TITLE
User can complete a test and view a score.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/Typing-Test#7]
# Motivation
User will be able to see how well they did typing the sentence.

# Task
- [x] Add container in html to hold score 
- [x] Define variable locating container
- [x] Define variable making score equal to 'correct' characters typed/total characters 
- [x] Return score as whole number
